project:
  type: website
  preview: 
    port: 7324
    watch-inputs: true


website:
  title: "HSI Conference and Workshop Series"


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    title-block-banner: true

metadata-files:
  - ./navigation/_sidebars.yml
  - ./navigation/_navbar.yml