project:
  type: website

website:
  title: "HSI Conference and Workshop Series"


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

metadata-files:
  - ./navigation/_sidebars.yml
  - ./navigation/_navbar.yml