project:
  type: website
  preview: 
    port: 7324
    watch-inputs: true


website:
  title: "HSI Conference and Workshop Series"
  favicon: assets/favicon.png
  description: "A series of conferences and workshops dedicated to Human Systems Integration (HSI), organized by the INCOSE HSI Working Group."
  site-url: "https://hsi-wg.github.io/conferences"
  site-path: "/conferences"
  image: assets/HSI2025-banner_twitter.png
  twitter-card: 
    creator: "@dhmmasson"
    card-style: summary_large_image
    image-alt: "HSI2025 announcement - November 5-7, 2025 - Online"
    image-width: 800
    image-height: 227
  open-graph: 
    locale: en_US
    site-name: "HSI Conference and Workshop Series"
  reader-mode: true
  cookie-consent: 
    prefs-text: "this site uses cookies to measure traffic and improve user experience through google analytics. There are no targeting or advertising cookies."
  google-analytics: 
    tracking-id: "G-3R59JBLZYP"
    anonymize-ip: true
    storage: cookies
  announcement: 
    content: "HSI2025 announcement - November 5-7, 2025 - Online" 
    position: below-navbar 
    type: primary
  
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    title-block-banner: true
    include-in-header: 
      text: <meta name="google-site-verification" content="vp6AQz54wI5Ae1U5aDpXwPAuEmCqFg__D8G0vBTiaFg" />

metadata-files:
  - ./navigation/_sidebars.yml
  - ./navigation/_navbar.yml